[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Add Burn & Drago info_queue messages
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'for _, v in ipairs(info_queue) do'
position = "before"
payload = '''
-- ellejokers. stuff :p
if (card) then
	-- Sophie Burn support
	if specific_vars and specific_vars.elle_burns then
		info_queue[#info_queue+1] = ellejokers.burn_desc()
	end
	-- Drago support
	if #SMODS.find_card("j_elle_drago", false)>0 then
		if _c.key == "m_wild" then info_queue[#info_queue+1] = G.P_CENTERS[G.GAME.current_round.elle_drago_ench] end
	end
end
'''
match_indent = true

# Fix SMODS incorrect challenge saving
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''G.challenge_tab = G.GAME and G.GAME.challenge and G.GAME.challenge_tab or nil'''
position = "after"
payload = '''
if type(G.challenge_tab) == "string" and G.GAME and G.GAME.challenge then
	G.challenge_tab = G.CHALLENGES[get_challenge_int_from_id(G.GAME.challenge or '') or ''] or {name = 'ERROR'}
end
'''
match_indent = true
overwrite = false

# Any stickers and custom values in challenges, copied from entropy and modified to add value support
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if v.eternal then card:set_eternal(true) end"
position = "before"
payload = '''
if v.stickers then
	for i, _v in ipairs(v.stickers) do
		SMODS.Stickers[_v]:apply(card, true)
	end
end
if v.ability then
	for k, v in pairs(v.ability) do
		card.ability[k] = v
	end
end
'''
match_indent = true

# same deal for actual game
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if v.eternal then _joker:set_eternal(true) end"
position = "before"
payload = '''
if v.stickers then
	for i, _v in ipairs(v.stickers) do
		SMODS.Stickers[_v]:apply(_joker, true)
	end
end
if v.ability then
	for k, v in pairs(v.ability) do
		_joker.ability[k] = v
	end
end
'''
match_indent = true

# Add "elle_pos_channel" channel to sound manager
[[patches]]
[patches.pattern]
target = "engine/sound_manager.lua"
pattern = "SMODS_Sounds = {}"
position = "after"
payload = '''
ELLE_POS_CHANNEL = love.thread.getChannel('elle_pos_channel')
'''
match_indent = true

# Add "elle_get_ambient" request type to sound manager
[[patches]]
[patches.pattern]
target = "engine/sound_manager.lua"
pattern = "elseif request.type == 'sound_source' then"
position = "before"
payload = '''
elseif request.type == 'elle_get_ambient' then
	ELLE_POS_CHANNEL:push(SOURCES[current_track][1])
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'card.lua'
pattern = 'bonus_h_dollars = self.ability.perma_h_dollars ~= 0 and self.ability.perma_h_dollars or nil,'
position = "after"
payload = 'elle_burns = self.ability.elle_burns ~= 0 and self.ability.elle_burns or nil,'
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = '-- TARGET: adding to hand effects'
position = 'before'
payload = '''
local effects = {}
SMODS.calculate_context({elle_add_card = true},effects)
local flags = SMODS.trigger_effects(effects)
print(flags)
if flags.elle_add_cards then
	for i,v in ipairs(flags.elle_add_cards) do
		if type(v)=="table" then
			v.area:remove_card(v)
			G.play:emplace(v)
			table.insert(final_scoring_hand,v)
		end
	end
end
'''
match_indent = true

# Juice Issues Patch from https://github.com/MathIsFun0/Talisman/blob/main/lovely.toml
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "func = (function() card:juice_up(0.7);return true end)"
position = "at"
payload = "func = (function() if card and card.juice_up then card:juice_up(0.7) end;return true end)"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if card then card:juice_up(0.8, 0.5) end"
position = "at"
payload = "if card and card.juice_up then card:juice_up(0.8, 0.5) end"
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "card:juice_up(0.6, 0.1)"
position = "at"
payload = "if card and card.juice_up then card:juice_up(0.6, 0.1) end"
match_indent = true