[manifest]
version = "0.1.0"
dump_lua = true
priority = 0

# Add Spearlamp & Drago info_queue messages
[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = 'for _, v in ipairs(info_queue) do'
position = "before"
payload = '''
-- ellejokers. stuff :p
if (card) then
	-- Spearlamp support
	if (#SMODS.find_card("j_elle_spearlamp", false)>0) then
		if (_c.key == "m_steel") then info_queue[#info_queue+1] = G.P_CENTERS.m_elle_slime end
		if (_c.key == "m_elle_slime") then info_queue[#info_queue+1] = G.P_CENTERS.m_steel end
	end
	-- Drago support
	if (#SMODS.find_card("j_elle_drago", false)>0) then
		if (_c.key == "m_wild") then info_queue[#info_queue+1] = G.P_CENTERS[G.GAME.current_round.elle_drago_ench] end
	end
end
'''
match_indent = true

# Fix SMODS incorrect challenge saving
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = '''G.challenge_tab = G.GAME and G.GAME.challenge and G.GAME.challenge_tab or nil'''
position = "after"
payload = '''
if type(G.challenge_tab) == "string" and G.GAME and G.GAME.challenge then
    G.challenge_tab = G.CHALLENGES[get_challenge_int_from_id(G.GAME.challenge or '') or ''] or {name = 'ERROR'}
end
'''
match_indent = true
overwrite = false

# Any stickers and custom values in challenges, copied from entropy and modified to add value support
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "if v.eternal then card:set_eternal(true) end"
position = "before"
payload = '''
if v.stickers then
	for i, _v in ipairs(v.stickers) do
		SMODS.Stickers[_v]:apply(card, true)
	end
end
if v.ability then
	for k, v in pairs(v.ability) do
		card.ability[k] = v
	end
end
'''
match_indent = true

# same deal for actual game
[[patches]]
[patches.pattern]
target = "game.lua"
pattern = "if v.eternal then _joker:set_eternal(true) end"
position = "before"
payload = '''
if v.stickers then
	for i, _v in ipairs(v.stickers) do
		SMODS.Stickers[_v]:apply(_joker, true)
	end
end
if v.ability then
	for k, v in pairs(v.ability) do
		_joker.ability[k] = v
	end
end
'''
match_indent = true

# Add "elle_pos_channel" channel to sound manager
[[patches]]
[patches.pattern]
target = "engine/sound_manager.lua"
pattern = "SMODS_Sounds = {}"
position = "after"
payload = '''
ELLE_POS_CHANNEL = love.thread.getChannel('elle_pos_channel')
'''
match_indent = true

# Add "elle_get_ambient" request type to sound manager
[[patches]]
[patches.pattern]
target = "engine/sound_manager.lua"
pattern = "elseif request.type == 'sound_source' then"
position = "before"
payload = '''
elseif request.type == 'elle_get_ambient' then
	ELLE_POS_CHANNEL:push(SOURCES[current_track][1])
'''
match_indent = true

# Add debug give for resident cards
[[patches]]
[patches.pattern]
target = "engine/controller.lua"
pattern = 'if key == "3" then'
position = "after"
payload = '''
if _card.ability.set == 'elle_Resident' and G.elle_resident_area and #G.elle_resident_area.cards < G.elle_resident_area.config.card_limit then
    SMODS.add_card({area = G.elle_resident_area, key = _card.config.center.key})
    _card:set_sprites(_card.config.center)
end
'''
match_indent = true

# Add resident calculation
[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "-- TARGET: add your own CardAreas for joker evaluation"
position = "after"
payload = '''
table.insert(t,G.elle_resident_area,1)
'''
match_indent = true

# Add residents appearing in shop
[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "for _,v in ipairs(SMODS.ConsumableType.obj_buffer) do"
position = "before"
payload = 'total_rate = total_rate + G.GAME.elle_resident_rate'
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = "for _, v in ipairs(rates) do"
position = "before"
payload = "table.insert(rates, {type = 'elle_Resident', val = G.GAME.elle_resident_rate})"
match_indent = true

[[patches]]
[patches.pattern]
target = '=[SMODS _ "src/utils/weights.lua"]'
pattern = "for _,v in ipairs(SMODS.ConsumableType.obj_buffer) do"
position = "before"
payload = "args.types[#args.types + 1] = 'elle_Resident'"
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/common_events.lua'
pattern = "elseif _type == 'Edition' then _pool[#_pool + 1] = \"e_foil\""
position = "after"
payload = "elseif _type == 'elle_Resident' then _pool[#_pool + 1] = 'elle_r_elle_chloe'"
match_indent = true

# Put residents in the correct area when buying from the shop
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "G.jokers:emplace(c1)"
position = 'at'
payload = '''
if c1.ability.set == "elle_Resident" then
    G.elle_resident_area:emplace(c1)
else
    G.jokers:emplace(c1)
end
'''
match_indent = true

# Let residents get debuffed by blinds
[[patches]]
[patches.pattern]
target = "blind.lua"
pattern = "--add new debuffs"
position = 'after'
payload = '''
for _, v in ipairs(G.elle_resident_area.cards) do
    if not reset then self:debuff_card(v, true) end
end
'''
match_indent = true
